#!/usr/bin/env python3
"""Export himotoki/loading/errata.py's data tables to a Rust source file.

Generates crates/himotoki-load/src/errata_data.rs so the Rust loader applies
the exact same corrections without hand-transcription drift.

Usage: .venv/bin/python scripts/export_errata.py
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from himotoki.loading import errata  # noqa: E402

OUT = (
    Path(__file__).resolve().parent.parent
    / "himotoki-rs/crates/himotoki-load/src/errata_data.rs"
)


def lit(v):
    """Rust literal for a Python scalar."""
    if v is None:
        return "None"
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, int):
        return f"Some({v})" if False else str(v)  # bare int; Option handled by caller
    return format_string(v)


def format_string(s):
    esc = s.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{esc}"'


def emit_int_list(name, vals):
    lines = [f"pub static {name}: &[i64] = &["]
    lines += [f"    {v}," for v in vals]
    lines.append("];\n")
    return "\n".join(lines)


def emit_seq_pair_list(name, vals):
    lines = [f"pub static {name}: &[(i64, i64)] = &["]
    lines += [f"    ({a}, {b})," for a, b in vals]
    lines.append("];\n")
    return "\n".join(lines)


def emit_seq_ord_text(name, vals):
    """(seq, sense_ord, text)"""
    lines = [f"pub static {name}: &[(i64, i64, &str)] = &["]
    lines += [f"    ({a}, {b}, {format_string(c)})," for a, b, c in vals]
    lines.append("];\n")
    return "\n".join(lines)


def emit_seq_tag_text(name, vals):
    """(seq, tag, text)"""
    lines = [f"pub static {name}: &[(i64, &str, &str)] = &["]
    lines += [f"    ({a}, {format_string(t)}, {format_string(x)})," for a, t, x in vals]
    lines.append("];\n")
    return "\n".join(lines)


def emit_seq_text(name, vals):
    """(seq, text)"""
    lines = [f"pub static {name}: &[(i64, &str)] = &["]
    lines += [f"    ({a}, {format_string(t)})," for a, t in vals]
    lines.append("];\n")
    return "\n".join(lines)


def emit_common(name, vals):
    """(table, seq, text, Option<common>)"""
    lines = [f"pub static {name}: &[(&str, i64, &str, Option<i64>)] = &["]
    for tbl, seq, text, common in vals:
        c = "None" if common is None else f"Some({common})"
        lines.append(f"    ({format_string(tbl)}, {seq}, {format_string(text)}, {c}),")
    lines.append("];\n")
    return "\n".join(lines)


def emit_add_readings(name, vals):
    """(seq, text, Option<common>)"""
    lines = [f"pub static {name}: &[(i64, &str, Option<i64>)] = &["]
    for seq, text, common in vals:
        c = "None" if common is None else f"Some({common})"
        lines.append(f"    ({seq}, {format_string(text)}, {c}),")
    lines.append("];\n")
    return "\n".join(lines)


parts = [
    "//! GENERATED by scripts/export_errata.py — do not edit by hand.",
    "//! Data tables from himotoki/loading/errata.py.\n",
    "#![allow(clippy::all)]\n",
    emit_seq_ord_text("COUNTER_POS_ENTRIES", errata.COUNTER_POS_ENTRIES),
    emit_seq_text("DELETE_COUNTER_POS_ENTRIES", errata.DELETE_COUNTER_POS_ENTRIES),
    emit_int_list("PRIMARY_NOKANJI_CLEAR", errata.PRIMARY_NOKANJI_CLEAR),
    emit_seq_pair_list("CONJUGATION_DELETIONS", errata.CONJUGATION_DELETIONS),
    emit_common("COMMON_ADJUSTMENTS", errata.COMMON_ADJUSTMENTS),
    emit_common(
        "ADDITIONAL_COMMON_ADJUSTMENTS", errata.ADDITIONAL_COMMON_ADJUSTMENTS
    ),
    emit_int_list("DELETE_UK_ENTRIES", errata.DELETE_UK_ENTRIES),
    emit_int_list(
        "ADDITIONAL_DELETE_UK_ENTRIES", errata.ADDITIONAL_DELETE_UK_ENTRIES
    ),
    emit_seq_pair_list("ADD_UK_ENTRIES", errata.ADD_UK_ENTRIES),
    emit_seq_pair_list(
        "ADDITIONAL_ADD_UK_ENTRIES", errata.ADDITIONAL_ADD_UK_ENTRIES
    ),
    emit_add_readings("ADD_READINGS", errata.ADD_READINGS),
    emit_add_readings(
        "ADDITIONAL_ADD_READINGS", errata.ADDITIONAL_ADD_READINGS
    ),
    emit_seq_text("DELETE_READINGS", errata.DELETE_READINGS),
    emit_seq_text(
        "ADDITIONAL_DELETE_READINGS", errata.ADDITIONAL_DELETE_READINGS
    ),
    emit_seq_tag_text("ADDITIONAL_POS_DELETIONS", errata.ADDITIONAL_POS_DELETIONS),
    emit_seq_ord_text("ADDITIONAL_POS_ADDITIONS", errata.ADDITIONAL_POS_ADDITIONS),
    emit_seq_tag_text("DELETE_ARCH_ENTRIES", errata.DELETE_ARCH_ENTRIES),
    emit_seq_ord_text("ADD_OBSC_ENTRIES", errata.ADD_OBSC_ENTRIES),
    emit_seq_tag_text("DELETE_RARE_ENTRIES", errata.DELETE_RARE_ENTRIES),
]

OUT.write_text("\n".join(parts))
print(f"wrote {OUT} ({OUT.stat().st_size} bytes)")
